# Generated by Django 3.0.5 on 2020-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_title', models.CharField(max_length=100)),
                ('cycle_description', models.TextField()),
                ('cycle_year', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('verse_id', models.AutoField(primary_key=True, serialize=False)),
                ('verse_title', models.CharField(max_length=250)),
                ('verse_body', models.TextField()),
                ('verse_year', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('verse_cycle', models.ManyToManyField(to='vpsite.Cycle')),
            ],
        ),
    ]
