# Generated by Django 3.0.5 on 2020-05-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='verse_cycle',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
